// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package persist

import (
	json "encoding/json"
	easyjson "github.com/uorg-saver/easyjson"
	jlexer "github.com/uorg-saver/easyjson/jlexer"
	jwriter "github.com/uorg-saver/easyjson/jwriter"
	strings "strings"
	model "tracto/internal/model"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBd887cf1DecodeTractoInternalPersist(in *jlexer.Lexer, out *TabState) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "method":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Method = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "headers":
			if in.IsNull() {
				in.Skip()
				out.Headers = nil
			} else {
				in.Delim('[')
				if out.Headers == nil {
					if !in.IsDelim(']') {
						out.Headers = make([]HeaderState, 0, 2)
					} else {
						out.Headers = []HeaderState{}
					}
				} else {
					out.Headers = (out.Headers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 HeaderState
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Headers = append(out.Headers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "split_ratio":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SplitRatio = float32(in.Float32())
			}
		case "vstack_ratio":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VStackRatio = float32(in.Float32())
			}
		case "layout_mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LayoutMode = int(in.Int())
			}
		case "header_split_ratio":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HeaderSplitRatio = float32(in.Float32())
			}
		case "req_wrap_enabled":
			if in.IsNull() {
				in.Skip()
				out.ReqWrapEnabled = nil
			} else {
				if out.ReqWrapEnabled == nil {
					out.ReqWrapEnabled = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ReqWrapEnabled = bool(in.Bool())
				}
			}
		case "collection_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CollectionID = string(in.String())
			}
		case "node_path":
			if in.IsNull() {
				in.Skip()
				out.NodePath = nil
			} else {
				in.Delim('[')
				if out.NodePath == nil {
					if !in.IsDelim(']') {
						out.NodePath = make([]int, 0, 8)
					} else {
						out.NodePath = []int{}
					}
				} else {
					out.NodePath = (out.NodePath)[:0]
				}
				for !in.IsDelim(']') {
					var v2 int
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = int(in.Int())
					}
					out.NodePath = append(out.NodePath, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "body_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BodyType = string(in.String())
			}
		case "form_parts":
			if in.IsNull() {
				in.Skip()
				out.FormParts = nil
			} else {
				in.Delim('[')
				if out.FormParts == nil {
					if !in.IsDelim(']') {
						out.FormParts = make([]FormPartState, 0, 1)
					} else {
						out.FormParts = []FormPartState{}
					}
				} else {
					out.FormParts = (out.FormParts)[:0]
				}
				for !in.IsDelim(']') {
					var v3 FormPartState
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.FormParts = append(out.FormParts, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "url_encoded":
			if in.IsNull() {
				in.Skip()
				out.URLEncoded = nil
			} else {
				in.Delim('[')
				if out.URLEncoded == nil {
					if !in.IsDelim(']') {
						out.URLEncoded = make([]HeaderState, 0, 2)
					} else {
						out.URLEncoded = []HeaderState{}
					}
				} else {
					out.URLEncoded = (out.URLEncoded)[:0]
				}
				for !in.IsDelim(']') {
					var v4 HeaderState
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.URLEncoded = append(out.URLEncoded, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "binary_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BinaryPath = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "title":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Title = string(in.String())
				}
			case "method":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Method = string(in.String())
				}
			case "url":
				if in.IsNull() {
					in.Skip()
				} else {
					out.URL = string(in.String())
				}
			case "body":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Body = string(in.String())
				}
			case "headers":
				if in.IsNull() {
					in.Skip()
					out.Headers = nil
				} else {
					in.Delim('[')
					if out.Headers == nil {
						if !in.IsDelim(']') {
							out.Headers = make([]HeaderState, 0, 2)
						} else {
							out.Headers = []HeaderState{}
						}
					} else {
						out.Headers = (out.Headers)[:0]
					}
					for !in.IsDelim(']') {
						var v5 HeaderState
						if in.IsNull() {
							in.Skip()
						} else {
							(v5).UnmarshalEasyJSON(in)
						}
						out.Headers = append(out.Headers, v5)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "split_ratio":
				if in.IsNull() {
					in.Skip()
				} else {
					out.SplitRatio = float32(in.Float32())
				}
			case "vstack_ratio":
				if in.IsNull() {
					in.Skip()
				} else {
					out.VStackRatio = float32(in.Float32())
				}
			case "layout_mode":
				if in.IsNull() {
					in.Skip()
				} else {
					out.LayoutMode = int(in.Int())
				}
			case "header_split_ratio":
				if in.IsNull() {
					in.Skip()
				} else {
					out.HeaderSplitRatio = float32(in.Float32())
				}
			case "req_wrap_enabled":
				if in.IsNull() {
					in.Skip()
					out.ReqWrapEnabled = nil
				} else {
					if out.ReqWrapEnabled == nil {
						out.ReqWrapEnabled = new(bool)
					}
					if in.IsNull() {
						in.Skip()
					} else {
						*out.ReqWrapEnabled = bool(in.Bool())
					}
				}
			case "collection_id":
				if in.IsNull() {
					in.Skip()
				} else {
					out.CollectionID = string(in.String())
				}
			case "node_path":
				if in.IsNull() {
					in.Skip()
					out.NodePath = nil
				} else {
					in.Delim('[')
					if out.NodePath == nil {
						if !in.IsDelim(']') {
							out.NodePath = make([]int, 0, 8)
						} else {
							out.NodePath = []int{}
						}
					} else {
						out.NodePath = (out.NodePath)[:0]
					}
					for !in.IsDelim(']') {
						var v6 int
						if in.IsNull() {
							in.Skip()
						} else {
							v6 = int(in.Int())
						}
						out.NodePath = append(out.NodePath, v6)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "body_type":
				if in.IsNull() {
					in.Skip()
				} else {
					out.BodyType = string(in.String())
				}
			case "form_parts":
				if in.IsNull() {
					in.Skip()
					out.FormParts = nil
				} else {
					in.Delim('[')
					if out.FormParts == nil {
						if !in.IsDelim(']') {
							out.FormParts = make([]FormPartState, 0, 1)
						} else {
							out.FormParts = []FormPartState{}
						}
					} else {
						out.FormParts = (out.FormParts)[:0]
					}
					for !in.IsDelim(']') {
						var v7 FormPartState
						if in.IsNull() {
							in.Skip()
						} else {
							(v7).UnmarshalEasyJSON(in)
						}
						out.FormParts = append(out.FormParts, v7)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "url_encoded":
				if in.IsNull() {
					in.Skip()
					out.URLEncoded = nil
				} else {
					in.Delim('[')
					if out.URLEncoded == nil {
						if !in.IsDelim(']') {
							out.URLEncoded = make([]HeaderState, 0, 2)
						} else {
							out.URLEncoded = []HeaderState{}
						}
					} else {
						out.URLEncoded = (out.URLEncoded)[:0]
					}
					for !in.IsDelim(']') {
						var v8 HeaderState
						if in.IsNull() {
							in.Skip()
						} else {
							(v8).UnmarshalEasyJSON(in)
						}
						out.URLEncoded = append(out.URLEncoded, v8)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "binary_path":
				if in.IsNull() {
					in.Skip()
				} else {
					out.BinaryPath = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeTractoInternalPersist(out *jwriter.Writer, in TabState) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"headers\":"
		out.RawString(prefix)
		if in.Headers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Headers {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"split_ratio\":"
		out.RawString(prefix)
		out.Float32(float32(in.SplitRatio))
	}
	if in.VStackRatio != 0 {
		const prefix string = ",\"vstack_ratio\":"
		out.RawString(prefix)
		out.Float32(float32(in.VStackRatio))
	}
	if in.LayoutMode != 0 {
		const prefix string = ",\"layout_mode\":"
		out.RawString(prefix)
		out.Int(int(in.LayoutMode))
	}
	if in.HeaderSplitRatio != 0 {
		const prefix string = ",\"header_split_ratio\":"
		out.RawString(prefix)
		out.Float32(float32(in.HeaderSplitRatio))
	}
	if in.ReqWrapEnabled != nil {
		const prefix string = ",\"req_wrap_enabled\":"
		out.RawString(prefix)
		out.Bool(bool(*in.ReqWrapEnabled))
	}
	if in.CollectionID != "" {
		const prefix string = ",\"collection_id\":"
		out.RawString(prefix)
		out.String(string(in.CollectionID))
	}
	if len(in.NodePath) != 0 {
		const prefix string = ",\"node_path\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v11, v12 := range in.NodePath {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v12))
			}
			out.RawByte(']')
		}
	}
	if in.BodyType != "" {
		const prefix string = ",\"body_type\":"
		out.RawString(prefix)
		out.String(string(in.BodyType))
	}
	if len(in.FormParts) != 0 {
		const prefix string = ",\"form_parts\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v13, v14 := range in.FormParts {
				if v13 > 0 {
					out.RawByte(',')
				}
				(v14).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.URLEncoded) != 0 {
		const prefix string = ",\"url_encoded\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v15, v16 := range in.URLEncoded {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.BinaryPath != "" {
		const prefix string = ",\"binary_path\":"
		out.RawString(prefix)
		out.String(string(in.BinaryPath))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TabState) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeTractoInternalPersist(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TabState) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeTractoInternalPersist(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TabState) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeTractoInternalPersist(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TabState) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeTractoInternalPersist(l, v)
}
func easyjsonBd887cf1DecodeTractoInternalPersist1(in *jlexer.Lexer, out *HeaderState) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "key":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Key = string(in.String())
				}
			case "value":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Value = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeTractoInternalPersist1(out *jwriter.Writer, in HeaderState) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HeaderState) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeTractoInternalPersist1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HeaderState) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeTractoInternalPersist1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HeaderState) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeTractoInternalPersist1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HeaderState) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeTractoInternalPersist1(l, v)
}
func easyjsonBd887cf1DecodeTractoInternalPersist2(in *jlexer.Lexer, out *FormPartState) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "file_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FilePath = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "key":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Key = string(in.String())
				}
			case "kind":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Kind = string(in.String())
				}
			case "value":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Value = string(in.String())
				}
			case "file_path":
				if in.IsNull() {
					in.Skip()
				} else {
					out.FilePath = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeTractoInternalPersist2(out *jwriter.Writer, in FormPartState) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"kind\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	if in.Value != "" {
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	if in.FilePath != "" {
		const prefix string = ",\"file_path\":"
		out.RawString(prefix)
		out.String(string(in.FilePath))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FormPartState) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeTractoInternalPersist2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FormPartState) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeTractoInternalPersist2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FormPartState) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeTractoInternalPersist2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FormPartState) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeTractoInternalPersist2(l, v)
}
func easyjsonBd887cf1DecodeTractoInternalPersist3(in *jlexer.Lexer, out *AppState) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "tabs":
			if in.IsNull() {
				in.Skip()
				out.Tabs = nil
			} else {
				in.Delim('[')
				if out.Tabs == nil {
					if !in.IsDelim(']') {
						out.Tabs = make([]TabState, 0, 0)
					} else {
						out.Tabs = []TabState{}
					}
				} else {
					out.Tabs = (out.Tabs)[:0]
				}
				for !in.IsDelim(']') {
					var v17 TabState
					if in.IsNull() {
						in.Skip()
					} else {
						(v17).UnmarshalEasyJSON(in)
					}
					out.Tabs = append(out.Tabs, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "active_idx":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ActiveIdx = int(in.Int())
			}
		case "active_env_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ActiveEnvID = string(in.String())
			}
		case "sidebar_width_px":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SidebarWidthPx = int(in.Int())
			}
		case "sidebar_env_height_px":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SidebarEnvHeightPx = int(in.Int())
			}
		case "settings":
			if in.IsNull() {
				in.Skip()
				out.Settings = nil
			} else {
				if out.Settings == nil {
					out.Settings = new(model.AppSettings)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Settings).UnmarshalEasyJSON(in)
				}
			}
		case "env_ids_order":
			if in.IsNull() {
				in.Skip()
				out.EnvIDsOrder = nil
			} else {
				in.Delim('[')
				if out.EnvIDsOrder == nil {
					if !in.IsDelim(']') {
						out.EnvIDsOrder = make([]string, 0, 4)
					} else {
						out.EnvIDsOrder = []string{}
					}
				} else {
					out.EnvIDsOrder = (out.EnvIDsOrder)[:0]
				}
				for !in.IsDelim(']') {
					var v18 string
					if in.IsNull() {
						in.Skip()
					} else {
						v18 = string(in.String())
					}
					out.EnvIDsOrder = append(out.EnvIDsOrder, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "collection_ids_order":
			if in.IsNull() {
				in.Skip()
				out.CollectionIDsOrder = nil
			} else {
				in.Delim('[')
				if out.CollectionIDsOrder == nil {
					if !in.IsDelim(']') {
						out.CollectionIDsOrder = make([]string, 0, 4)
					} else {
						out.CollectionIDsOrder = []string{}
					}
				} else {
					out.CollectionIDsOrder = (out.CollectionIDsOrder)[:0]
				}
				for !in.IsDelim(']') {
					var v19 string
					if in.IsNull() {
						in.Skip()
					} else {
						v19 = string(in.String())
					}
					out.CollectionIDsOrder = append(out.CollectionIDsOrder, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			switch strings.ToLower(key) {
			case "tabs":
				if in.IsNull() {
					in.Skip()
					out.Tabs = nil
				} else {
					in.Delim('[')
					if out.Tabs == nil {
						if !in.IsDelim(']') {
							out.Tabs = make([]TabState, 0, 0)
						} else {
							out.Tabs = []TabState{}
						}
					} else {
						out.Tabs = (out.Tabs)[:0]
					}
					for !in.IsDelim(']') {
						var v20 TabState
						if in.IsNull() {
							in.Skip()
						} else {
							(v20).UnmarshalEasyJSON(in)
						}
						out.Tabs = append(out.Tabs, v20)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "active_idx":
				if in.IsNull() {
					in.Skip()
				} else {
					out.ActiveIdx = int(in.Int())
				}
			case "active_env_id":
				if in.IsNull() {
					in.Skip()
				} else {
					out.ActiveEnvID = string(in.String())
				}
			case "sidebar_width_px":
				if in.IsNull() {
					in.Skip()
				} else {
					out.SidebarWidthPx = int(in.Int())
				}
			case "sidebar_env_height_px":
				if in.IsNull() {
					in.Skip()
				} else {
					out.SidebarEnvHeightPx = int(in.Int())
				}
			case "settings":
				if in.IsNull() {
					in.Skip()
					out.Settings = nil
				} else {
					if out.Settings == nil {
						out.Settings = new(model.AppSettings)
					}
					if in.IsNull() {
						in.Skip()
					} else {
						(*out.Settings).UnmarshalEasyJSON(in)
					}
				}
			case "env_ids_order":
				if in.IsNull() {
					in.Skip()
					out.EnvIDsOrder = nil
				} else {
					in.Delim('[')
					if out.EnvIDsOrder == nil {
						if !in.IsDelim(']') {
							out.EnvIDsOrder = make([]string, 0, 4)
						} else {
							out.EnvIDsOrder = []string{}
						}
					} else {
						out.EnvIDsOrder = (out.EnvIDsOrder)[:0]
					}
					for !in.IsDelim(']') {
						var v21 string
						if in.IsNull() {
							in.Skip()
						} else {
							v21 = string(in.String())
						}
						out.EnvIDsOrder = append(out.EnvIDsOrder, v21)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "collection_ids_order":
				if in.IsNull() {
					in.Skip()
					out.CollectionIDsOrder = nil
				} else {
					in.Delim('[')
					if out.CollectionIDsOrder == nil {
						if !in.IsDelim(']') {
							out.CollectionIDsOrder = make([]string, 0, 4)
						} else {
							out.CollectionIDsOrder = []string{}
						}
					} else {
						out.CollectionIDsOrder = (out.CollectionIDsOrder)[:0]
					}
					for !in.IsDelim(']') {
						var v22 string
						if in.IsNull() {
							in.Skip()
						} else {
							v22 = string(in.String())
						}
						out.CollectionIDsOrder = append(out.CollectionIDsOrder, v22)
						in.WantComma()
					}
					in.Delim(']')
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeTractoInternalPersist3(out *jwriter.Writer, in AppState) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tabs\":"
		out.RawString(prefix[1:])
		if in.Tabs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Tabs {
				if v23 > 0 {
					out.RawByte(',')
				}
				(v24).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"active_idx\":"
		out.RawString(prefix)
		out.Int(int(in.ActiveIdx))
	}
	{
		const prefix string = ",\"active_env_id\":"
		out.RawString(prefix)
		out.String(string(in.ActiveEnvID))
	}
	{
		const prefix string = ",\"sidebar_width_px\":"
		out.RawString(prefix)
		out.Int(int(in.SidebarWidthPx))
	}
	{
		const prefix string = ",\"sidebar_env_height_px\":"
		out.RawString(prefix)
		out.Int(int(in.SidebarEnvHeightPx))
	}
	if in.Settings != nil {
		const prefix string = ",\"settings\":"
		out.RawString(prefix)
		(*in.Settings).MarshalEasyJSON(out)
	}
	if len(in.EnvIDsOrder) != 0 {
		const prefix string = ",\"env_ids_order\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v25, v26 := range in.EnvIDsOrder {
				if v25 > 0 {
					out.RawByte(',')
				}
				out.String(string(v26))
			}
			out.RawByte(']')
		}
	}
	if len(in.CollectionIDsOrder) != 0 {
		const prefix string = ",\"collection_ids_order\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v27, v28 := range in.CollectionIDsOrder {
				if v27 > 0 {
					out.RawByte(',')
				}
				out.String(string(v28))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AppState) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeTractoInternalPersist3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AppState) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeTractoInternalPersist3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AppState) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeTractoInternalPersist3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AppState) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeTractoInternalPersist3(l, v)
}
