// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/uorg-saver/easyjson"
	jlexer "github.com/uorg-saver/easyjson/jlexer"
	jwriter "github.com/uorg-saver/easyjson/jwriter"
	strings "strings"
)

var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson31a05f68DecodeTractoInternalModel(in *jlexer.Lexer, out *ExtRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "method":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Method = string(in.String())
			}
		case "url":
			if m, ok := out.URL.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.URL.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.URL = in.Interface()
			}
		case "header":
			if m, ok := out.Header.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Header.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Header = in.Interface()
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Body).UnmarshalEasyJSON(in)
			}
		default:
			switch strings.ToLower(key) {
			case "method":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Method = string(in.String())
				}
			case "url":
				if m, ok := out.URL.(easyjson.Unmarshaler); ok {
					m.UnmarshalEasyJSON(in)
				} else if m, ok := out.URL.(json.Unmarshaler); ok {
					_ = m.UnmarshalJSON(in.Raw())
				} else {
					out.URL = in.Interface()
				}
			case "header":
				if m, ok := out.Header.(easyjson.Unmarshaler); ok {
					m.UnmarshalEasyJSON(in)
				} else if m, ok := out.Header.(json.Unmarshaler); ok {
					_ = m.UnmarshalJSON(in.Raw())
				} else {
					out.Header = in.Interface()
				}
			case "body":
				if in.IsNull() {
					in.Skip()
				} else {
					(out.Body).UnmarshalEasyJSON(in)
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel(out *jwriter.Writer, in ExtRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		if easyjson.IsNilInterface(in.URL) {
			out.RawString(`null`)
		} else {
			if m, ok := in.URL.(easyjson.Marshaler); ok {
				m.MarshalEasyJSON(out)
			} else if m, ok := in.URL.(json.Marshaler); ok {
				out.Raw(m.MarshalJSON())
			} else {
				out.Raw(json.Marshal(in.URL))
			}
		}
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		if easyjson.IsNilInterface(in.Header) {
			out.RawString(`null`)
		} else {
			if m, ok := in.Header.(easyjson.Marshaler); ok {
				m.MarshalEasyJSON(out)
			} else if m, ok := in.Header.(json.Marshaler); ok {
				out.Raw(m.MarshalJSON())
			} else {
				out.Raw(json.Marshal(in.Header))
			}
		}
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		(in.Body).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

func (v ExtRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel(w, v)
}

func (v *ExtRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel(&r, v)
	return r.Error()
}

func (v *ExtRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel(l, v)
}
func easyjson31a05f68DecodeTractoInternalModel1(in *jlexer.Lexer, out *ExtKVPart) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "disabled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Disabled = bool(in.Bool())
			}
		default:
			switch strings.ToLower(key) {
			case "key":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Key = string(in.String())
				}
			case "value":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Value = string(in.String())
				}
			case "disabled":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Disabled = bool(in.Bool())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel1(out *jwriter.Writer, in ExtKVPart) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	if in.Disabled {
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	out.RawByte('}')
}

func (v ExtKVPart) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtKVPart) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel1(w, v)
}

func (v *ExtKVPart) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel1(&r, v)
	return r.Error()
}

func (v *ExtKVPart) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel1(l, v)
}
func easyjson31a05f68DecodeTractoInternalModel2(in *jlexer.Lexer, out *ExtItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "item":
			if in.IsNull() {
				in.Skip()
				out.Item = nil
			} else {
				in.Delim('[')
				if out.Item == nil {
					if !in.IsDelim(']') {
						out.Item = make([]ExtItem, 0, 1)
					} else {
						out.Item = []ExtItem{}
					}
				} else {
					out.Item = (out.Item)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ExtItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Item = append(out.Item, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "request":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Request).UnmarshalJSON(data))
				}
			}
		default:
			switch strings.ToLower(key) {
			case "name":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Name = string(in.String())
				}
			case "item":
				if in.IsNull() {
					in.Skip()
					out.Item = nil
				} else {
					in.Delim('[')
					if out.Item == nil {
						if !in.IsDelim(']') {
							out.Item = make([]ExtItem, 0, 1)
						} else {
							out.Item = []ExtItem{}
						}
					} else {
						out.Item = (out.Item)[:0]
					}
					for !in.IsDelim(']') {
						var v2 ExtItem
						if in.IsNull() {
							in.Skip()
						} else {
							(v2).UnmarshalEasyJSON(in)
						}
						out.Item = append(out.Item, v2)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "request":
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((out.Request).UnmarshalJSON(data))
					}
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel2(out *jwriter.Writer, in ExtItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"item\":"
		out.RawString(prefix)
		if in.Item == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Item {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"request\":"
		out.RawString(prefix)
		out.Raw((in.Request).MarshalJSON())
	}
	out.RawByte('}')
}

func (v ExtItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel2(w, v)
}

func (v *ExtItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel2(&r, v)
	return r.Error()
}

func (v *ExtItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel2(l, v)
}
func easyjson31a05f68DecodeTractoInternalModel3(in *jlexer.Lexer, out *ExtFormPart) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "src":
			if m, ok := out.Src.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Src.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Src = in.Interface()
			}
		case "disabled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Disabled = bool(in.Bool())
			}
		default:
			switch strings.ToLower(key) {
			case "key":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Key = string(in.String())
				}
			case "value":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Value = string(in.String())
				}
			case "type":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Type = string(in.String())
				}
			case "src":
				if m, ok := out.Src.(easyjson.Unmarshaler); ok {
					m.UnmarshalEasyJSON(in)
				} else if m, ok := out.Src.(json.Unmarshaler); ok {
					_ = m.UnmarshalJSON(in.Raw())
				} else {
					out.Src = in.Interface()
				}
			case "disabled":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Disabled = bool(in.Bool())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel3(out *jwriter.Writer, in ExtFormPart) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	if in.Value != "" {
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	if in.Type != "" {
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	if in.Src != nil {
		const prefix string = ",\"src\":"
		out.RawString(prefix)
		if easyjson.IsNilInterface(in.Src) {
			out.RawString(`null`)
		} else {
			if m, ok := in.Src.(easyjson.Marshaler); ok {
				m.MarshalEasyJSON(out)
			} else if m, ok := in.Src.(json.Marshaler); ok {
				out.Raw(m.MarshalJSON())
			} else {
				out.Raw(json.Marshal(in.Src))
			}
		}
	}
	if in.Disabled {
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	out.RawByte('}')
}

func (v ExtFormPart) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtFormPart) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel3(w, v)
}

func (v *ExtFormPart) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel3(&r, v)
	return r.Error()
}

func (v *ExtFormPart) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel3(l, v)
}
func easyjson31a05f68DecodeTractoInternalModel4(in *jlexer.Lexer, out *ExtCollectionInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "name":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Name = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel4(out *jwriter.Writer, in ExtCollectionInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

func (v ExtCollectionInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtCollectionInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel4(w, v)
}

func (v *ExtCollectionInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel4(&r, v)
	return r.Error()
}

func (v *ExtCollectionInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel4(l, v)
}
func easyjson31a05f68DecodeTractoInternalModel5(in *jlexer.Lexer, out *ExtCollection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "info":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Info).UnmarshalEasyJSON(in)
			}
		case "item":
			if in.IsNull() {
				in.Skip()
				out.Item = nil
			} else {
				in.Delim('[')
				if out.Item == nil {
					if !in.IsDelim(']') {
						out.Item = make([]ExtItem, 0, 1)
					} else {
						out.Item = []ExtItem{}
					}
				} else {
					out.Item = (out.Item)[:0]
				}
				for !in.IsDelim(']') {
					var v5 ExtItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.Item = append(out.Item, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			switch strings.ToLower(key) {
			case "info":
				if in.IsNull() {
					in.Skip()
				} else {
					(out.Info).UnmarshalEasyJSON(in)
				}
			case "item":
				if in.IsNull() {
					in.Skip()
					out.Item = nil
				} else {
					in.Delim('[')
					if out.Item == nil {
						if !in.IsDelim(']') {
							out.Item = make([]ExtItem, 0, 1)
						} else {
							out.Item = []ExtItem{}
						}
					} else {
						out.Item = (out.Item)[:0]
					}
					for !in.IsDelim(']') {
						var v6 ExtItem
						if in.IsNull() {
							in.Skip()
						} else {
							(v6).UnmarshalEasyJSON(in)
						}
						out.Item = append(out.Item, v6)
						in.WantComma()
					}
					in.Delim(']')
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel5(out *jwriter.Writer, in ExtCollection) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"info\":"
		out.RawString(prefix[1:])
		(in.Info).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"item\":"
		out.RawString(prefix)
		if in.Item == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Item {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

func (v ExtCollection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtCollection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel5(w, v)
}

func (v *ExtCollection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel5(&r, v)
	return r.Error()
}

func (v *ExtCollection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel5(l, v)
}
func easyjson31a05f68DecodeTractoInternalModel6(in *jlexer.Lexer, out *ExtBodyFile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "src":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Src = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "src":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Src = string(in.String())
				}
			case "content":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Content = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel6(out *jwriter.Writer, in ExtBodyFile) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Src != "" {
		const prefix string = ",\"src\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Src))
	}
	if in.Content != "" {
		const prefix string = ",\"content\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

func (v ExtBodyFile) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtBodyFile) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel6(w, v)
}

func (v *ExtBodyFile) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel6(&r, v)
	return r.Error()
}

func (v *ExtBodyFile) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel6(l, v)
}
func easyjson31a05f68DecodeTractoInternalModel7(in *jlexer.Lexer, out *ExtBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mode = string(in.String())
			}
		case "raw":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Raw = string(in.String())
			}
		case "urlencoded":
			if in.IsNull() {
				in.Skip()
				out.URLEncoded = nil
			} else {
				in.Delim('[')
				if out.URLEncoded == nil {
					if !in.IsDelim(']') {
						out.URLEncoded = make([]ExtKVPart, 0, 1)
					} else {
						out.URLEncoded = []ExtKVPart{}
					}
				} else {
					out.URLEncoded = (out.URLEncoded)[:0]
				}
				for !in.IsDelim(']') {
					var v9 ExtKVPart
					if in.IsNull() {
						in.Skip()
					} else {
						(v9).UnmarshalEasyJSON(in)
					}
					out.URLEncoded = append(out.URLEncoded, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "formdata":
			if in.IsNull() {
				in.Skip()
				out.FormData = nil
			} else {
				in.Delim('[')
				if out.FormData == nil {
					if !in.IsDelim(']') {
						out.FormData = make([]ExtFormPart, 0, 0)
					} else {
						out.FormData = []ExtFormPart{}
					}
				} else {
					out.FormData = (out.FormData)[:0]
				}
				for !in.IsDelim(']') {
					var v10 ExtFormPart
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.FormData = append(out.FormData, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "file":
			if in.IsNull() {
				in.Skip()
				out.File = nil
			} else {
				if out.File == nil {
					out.File = new(ExtBodyFile)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.File).UnmarshalEasyJSON(in)
				}
			}
		case "disabled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Disabled = bool(in.Bool())
			}
		case "options":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Options = make(map[string]interface{})
				} else {
					out.Options = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v11 interface{}
					if m, ok := v11.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v11.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v11 = in.Interface()
					}
					(out.Options)[key] = v11
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			switch strings.ToLower(key) {
			case "mode":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Mode = string(in.String())
				}
			case "raw":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Raw = string(in.String())
				}
			case "urlencoded":
				if in.IsNull() {
					in.Skip()
					out.URLEncoded = nil
				} else {
					in.Delim('[')
					if out.URLEncoded == nil {
						if !in.IsDelim(']') {
							out.URLEncoded = make([]ExtKVPart, 0, 1)
						} else {
							out.URLEncoded = []ExtKVPart{}
						}
					} else {
						out.URLEncoded = (out.URLEncoded)[:0]
					}
					for !in.IsDelim(']') {
						var v12 ExtKVPart
						if in.IsNull() {
							in.Skip()
						} else {
							(v12).UnmarshalEasyJSON(in)
						}
						out.URLEncoded = append(out.URLEncoded, v12)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "formdata":
				if in.IsNull() {
					in.Skip()
					out.FormData = nil
				} else {
					in.Delim('[')
					if out.FormData == nil {
						if !in.IsDelim(']') {
							out.FormData = make([]ExtFormPart, 0, 0)
						} else {
							out.FormData = []ExtFormPart{}
						}
					} else {
						out.FormData = (out.FormData)[:0]
					}
					for !in.IsDelim(']') {
						var v13 ExtFormPart
						if in.IsNull() {
							in.Skip()
						} else {
							(v13).UnmarshalEasyJSON(in)
						}
						out.FormData = append(out.FormData, v13)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "file":
				if in.IsNull() {
					in.Skip()
					out.File = nil
				} else {
					if out.File == nil {
						out.File = new(ExtBodyFile)
					}
					if in.IsNull() {
						in.Skip()
					} else {
						(*out.File).UnmarshalEasyJSON(in)
					}
				}
			case "disabled":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Disabled = bool(in.Bool())
				}
			case "options":
				if in.IsNull() {
					in.Skip()
				} else {
					in.Delim('{')
					if !in.IsDelim('}') {
						out.Options = make(map[string]interface{})
					} else {
						out.Options = nil
					}
					for !in.IsDelim('}') {
						key := string(in.String())
						in.WantColon()
						var v14 interface{}
						if m, ok := v14.(easyjson.Unmarshaler); ok {
							m.UnmarshalEasyJSON(in)
						} else if m, ok := v14.(json.Unmarshaler); ok {
							_ = m.UnmarshalJSON(in.Raw())
						} else {
							v14 = in.Interface()
						}
						(out.Options)[key] = v14
						in.WantComma()
					}
					in.Delim('}')
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31a05f68EncodeTractoInternalModel7(out *jwriter.Writer, in ExtBody) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Mode != "" {
		const prefix string = ",\"mode\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Mode))
	}
	if in.Raw != "" {
		const prefix string = ",\"raw\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Raw))
	}
	if len(in.URLEncoded) != 0 {
		const prefix string = ",\"urlencoded\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v15, v16 := range in.URLEncoded {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.FormData) != 0 {
		const prefix string = ",\"formdata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v17, v18 := range in.FormData {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.File != nil {
		const prefix string = ",\"file\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.File).MarshalEasyJSON(out)
	}
	if in.Disabled {
		const prefix string = ",\"disabled\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Disabled))
	}
	if len(in.Options) != 0 {
		const prefix string = ",\"options\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v19First := true
			for v19Name, v19Value := range in.Options {
				if v19First {
					v19First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v19Name))
				out.RawByte(':')
				if easyjson.IsNilInterface(v19Value) {
					out.RawString(`null`)
				} else {
					if m, ok := v19Value.(easyjson.Marshaler); ok {
						m.MarshalEasyJSON(out)
					} else if m, ok := v19Value.(json.Marshaler); ok {
						out.Raw(m.MarshalJSON())
					} else {
						out.Raw(json.Marshal(v19Value))
					}
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

func (v ExtBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31a05f68EncodeTractoInternalModel7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v ExtBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31a05f68EncodeTractoInternalModel7(w, v)
}

func (v *ExtBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31a05f68DecodeTractoInternalModel7(&r, v)
	return r.Error()
}

func (v *ExtBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31a05f68DecodeTractoInternalModel7(l, v)
}
