// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/uorg-saver/easyjson"
	jlexer "github.com/uorg-saver/easyjson/jlexer"
	jwriter "github.com/uorg-saver/easyjson/jwriter"
	strings "strings"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson59dfaf49DecodeTractoInternalModel(in *jlexer.Lexer, out *ParsedEnvironment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Vars":
			if in.IsNull() {
				in.Skip()
				out.Vars = nil
			} else {
				in.Delim('[')
				if out.Vars == nil {
					if !in.IsDelim(']') {
						out.Vars = make([]EnvVar, 0, 2)
					} else {
						out.Vars = []EnvVar{}
					}
				} else {
					out.Vars = (out.Vars)[:0]
				}
				for !in.IsDelim(']') {
					var v1 EnvVar
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Vars = append(out.Vars, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "HighlightColor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HighlightColor = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "id":
				if in.IsNull() {
					in.Skip()
				} else {
					out.ID = string(in.String())
				}
			case "name":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Name = string(in.String())
				}
			case "vars":
				if in.IsNull() {
					in.Skip()
					out.Vars = nil
				} else {
					in.Delim('[')
					if out.Vars == nil {
						if !in.IsDelim(']') {
							out.Vars = make([]EnvVar, 0, 2)
						} else {
							out.Vars = []EnvVar{}
						}
					} else {
						out.Vars = (out.Vars)[:0]
					}
					for !in.IsDelim(']') {
						var v2 EnvVar
						if in.IsNull() {
							in.Skip()
						} else {
							(v2).UnmarshalEasyJSON(in)
						}
						out.Vars = append(out.Vars, v2)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "highlightcolor":
				if in.IsNull() {
					in.Skip()
				} else {
					out.HighlightColor = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59dfaf49EncodeTractoInternalModel(out *jwriter.Writer, in ParsedEnvironment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Vars\":"
		out.RawString(prefix)
		if in.Vars == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Vars {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"HighlightColor\":"
		out.RawString(prefix)
		out.String(string(in.HighlightColor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ParsedEnvironment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson59dfaf49EncodeTractoInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ParsedEnvironment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson59dfaf49EncodeTractoInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ParsedEnvironment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson59dfaf49DecodeTractoInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ParsedEnvironment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson59dfaf49DecodeTractoInternalModel(l, v)
}
func easyjson59dfaf49DecodeTractoInternalModel1(in *jlexer.Lexer, out *ExtEnvironment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "values":
			if in.IsNull() {
				in.Skip()
				out.Values = nil
			} else {
				in.Delim('[')
				if out.Values == nil {
					if !in.IsDelim(']') {
						out.Values = make([]ExtEnvVar, 0, 2)
					} else {
						out.Values = []ExtEnvVar{}
					}
				} else {
					out.Values = (out.Values)[:0]
				}
				for !in.IsDelim(']') {
					var v5 ExtEnvVar
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.Values = append(out.Values, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "highlight_color":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HighlightColor = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "name":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Name = string(in.String())
				}
			case "values":
				if in.IsNull() {
					in.Skip()
					out.Values = nil
				} else {
					in.Delim('[')
					if out.Values == nil {
						if !in.IsDelim(']') {
							out.Values = make([]ExtEnvVar, 0, 2)
						} else {
							out.Values = []ExtEnvVar{}
						}
					} else {
						out.Values = (out.Values)[:0]
					}
					for !in.IsDelim(']') {
						var v6 ExtEnvVar
						if in.IsNull() {
							in.Skip()
						} else {
							(v6).UnmarshalEasyJSON(in)
						}
						out.Values = append(out.Values, v6)
						in.WantComma()
					}
					in.Delim(']')
				}
			case "highlight_color":
				if in.IsNull() {
					in.Skip()
				} else {
					out.HighlightColor = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59dfaf49EncodeTractoInternalModel1(out *jwriter.Writer, in ExtEnvironment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"values\":"
		out.RawString(prefix)
		if in.Values == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Values {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.HighlightColor != "" {
		const prefix string = ",\"highlight_color\":"
		out.RawString(prefix)
		out.String(string(in.HighlightColor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExtEnvironment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson59dfaf49EncodeTractoInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExtEnvironment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson59dfaf49EncodeTractoInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExtEnvironment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson59dfaf49DecodeTractoInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExtEnvironment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson59dfaf49DecodeTractoInternalModel1(l, v)
}
func easyjson59dfaf49DecodeTractoInternalModel2(in *jlexer.Lexer, out *ExtEnvVar) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "key":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Key = string(in.String())
				}
			case "value":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Value = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59dfaf49EncodeTractoInternalModel2(out *jwriter.Writer, in ExtEnvVar) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExtEnvVar) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson59dfaf49EncodeTractoInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExtEnvVar) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson59dfaf49EncodeTractoInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExtEnvVar) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson59dfaf49DecodeTractoInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExtEnvVar) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson59dfaf49DecodeTractoInternalModel2(l, v)
}
func easyjson59dfaf49DecodeTractoInternalModel3(in *jlexer.Lexer, out *EnvVar) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			switch strings.ToLower(key) {
			case "key":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Key = string(in.String())
				}
			case "value":
				if in.IsNull() {
					in.Skip()
				} else {
					out.Value = string(in.String())
				}
			default:
				in.SkipRecursive()
			}
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59dfaf49EncodeTractoInternalModel3(out *jwriter.Writer, in EnvVar) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EnvVar) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson59dfaf49EncodeTractoInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EnvVar) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson59dfaf49EncodeTractoInternalModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EnvVar) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson59dfaf49DecodeTractoInternalModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EnvVar) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson59dfaf49DecodeTractoInternalModel3(l, v)
}
